#!/bin/sh
_usage()
{
	cat << EOT
Usage: `basename $0` [OPTION...] package-resource-name
Makes local copy of already uploaded package by group id and name in CQ Package
Manager using instance URL.
 
Examples:
  cqcp -u admin pack            # Get package copy named pack
  cqcp -u admin -g GRP pack     # Get package copy named pack in group GRP
  cqcp -i http://localhost:5510 # Get package copy for localhost instance on
       -g com.group stuff       # tcp port 5510 named stuff in group:com.group
       -p secret                # with password provided: secret 
       -o alt-stuff.zip         # with local name specified as alt-stuff.zip

Options:

  -u                    use specified usernamed for connection
  -p                    use provided password for authentication
  -i                    use specified instance URL to connect
  -g                    locate package by additional group ID  
  -o                    store local copy of package using provided filename
                        or path

EOT
exit 1
}

CWD=`dirname $0`
API="$CWD/cqapi"
APITEST=`$API -P`
if [ $? -ne 0 ]
then
	echo "Fatal: cannot find or test cqapi command" >&2
	exit 1
fi

CURLBIN=`$API -c`
if [ $? -ne 0 ]
then
	echo "Fatal: cannot find curl" >&2
	exit 1
fi


# API common options
cmdapi=`    $API -P $@`
username=`  echo "${cmdapi}" | cut -f1`
password=`  echo "${cmdapi}" | cut -f2`
instance=`  echo "${cmdapi}" | cut -f3`
passed=`    echo "${cmdapi}" | cut -f4`
apigetopts=`echo "${cmdapi}" | cut -f5`

# Custom arguments
while getopts ":o:g:${apigetopts}" opt; do
  case $opt in
     g)  
      group="$OPTARG";;
     o)  
      outfile="$OPTARG";;
    \?)
      echo "Invalid option: -$OPTARG" >&2; _usage;;
     :)
      echo "Option -$OPTARG requires an argument." >&2; _usage;;
  esac
done
shift $((OPTIND-1))

if [ $# -ge 2 -o $passed -eq 0 ];
then
	_usage
fi
name=$1

if [ -z  "${group}" ]
then
        group_part=""
else
        group_part="${group}/"
fi

if [ -z "$file" ]
then
        redirection="-o ${name}.zip"
else
        redirection="-o $outfile"
fi


REFERER="$instance/etc/packages"
AUTH="$username:$password"
FILEPATH="/crx/packmgr/service.jsp"
REFERERHEADER="Referer: $REFERER"

$CURLBIN \
        -s \
        -u "$AUTH" \
        -H "$REFERERHEADER" \
        -F cmd=get \
        ${group_arg} \
        -F name=${name} \
        ${redirection} \
        "$instance${FILEPATH}"

EXITCODE=$?
$API -C $EXITCODE
exit $EXITCODE

