#!/bin/sh
# CQ Unix Toolkit
# Copyright (C) 2013 Cognifide Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
INSTALL_DIR="/usr/local/bin"
if [ "${USER}" != 'root' ]
then
    echo "Please execute with superuser privileges" >&2
    exit 1
fi

dir=`dirname $0`
basedir=`readlink -f $dir`
echo "I assume that CQ UNIX tools are in: $basedir"
echo "Installing symbolic links in: $INSTALL_DIR"
if [ ! -d "$INSTALL_DIR" ] 
then
    echo "Cannot find $INSTALL_DIR directory" >&2
    exit 1
fi

read -p "Do you want to continue (Y/N) ?" REPLY
if [ "${REPLY}" = "Y" ] 
then
    for cmd in `ls -1 cq*`
    do
        ln -vs "$basedir/$cmd" "$INSTALL_DIR/$cmd"
    done
    echo "Installation finished"
else
    echo "Aborted"
fi
