#!/bin/sh
# CQ Unix Toolkit
# Copyright (C) 2013 Cognifide Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
INSTALL_DIR="/usr/local/bin"
if [ "${USER}" != 'root' ]
then
    echo "Please execute with superuser privileges" >&2
    exit 1
fi


dir=`dirname $0`
basedir=`readlink -f $dir`
echo "I assume that CQ UNIX tools are in: $basedir"
echo "Installing symbolic links in: $INSTALL_DIR"
if [ ! -d "$INSTALL_DIR" ] 
then
    echo "Cannot find $INSTALL_DIR directory" >&2
    exit 1
fi

existing_tools=""
warning=0
cmds=""
for cmd in `ls -1 cq*`
do
    if [ -f "$INSTALL_DIR/$cmd" ]
    then
        if [ -L "$INSTALL_DIR/$cmd" ]
        then
            target=`readlink -f $INSTALL_DIR/$cmd`
            output="$INSTALL_DIR/$cmd is currently linking to: ${target}\n"
        else
            output="$INSTALL_DIR/$cmd is currently a binary file\n"
        fi
        existing_tools="${existing_tools}${output}"
        warning=1
    fi
    cmds="${cmds} $cmd"
done
echo "${existing_tools}"

options=""
if [ $warning -eq 1 ]
then
    read -p "Do you want to replace (a)ll links, (i)ndividual ones or quit (A/I/Q) ?" REPLY
    if [ "${REPLY}" != "A" -a "${REPLY}" != "a" -a "${REPLY}" != "i" -a "${REPLY}" != "I"  ]
    then
        echo "Aborted"
        exit 1;
    fi
    [ "${REPLY}" = "A" -o "${REPLY}" = "a" ] && options="-f" || options="-i"
else
    read -p "Do you want to continue (Y/N) ?" REPLY
    if [ "${REPLY}" != "Y" -a "${REPLY}" != "y" ]
    then
        echo "Aborted"
        exit 1;
    fi
fi

for cmd in $cmds
do
    ln $options  -vs "$basedir/$cmd" "$INSTALL_DIR/$cmd"
done
echo "Installation finished."
